"""Generate `providers.gitleaks.yaml` from gitleaks' rule catalogue, pinned to one commit.

    uv run python policies/rules/import_gitleaks.py            # writes providers.gitleaks.yaml

Gitleaks (MIT) keeps ~220 rules for the credential formats of named providers: distinctive prefixes
(`glpat-`, `xoxb-`, `dop_v1_`) and provider-name-plus-value patterns. Importing them, rather than
hand-writing one provider at a time, is how the secrets ruleset covers formats nobody here listed.
Changing `COMMIT` and re-running is a reviewed change like any other ruleset edit (bump the policy
version, regenerate the baselines).

What is carried over, per rule: the regex (Go RE2 syntax, compiled with RE2 so matching stays linear
in the input), the secret group (gitleaks reports the first capture group when there is one), the entropy
floor, the keywords (a cheap prefilter: the rule only runs when one appears), and value allowlists.
Left out: `generic-api-key` (the hand-written context rules in secrets.v2.yaml cover that ground with
this project's own decoys), rules scoped to file paths (kubernetes secrets, Terraform, NuGet, Freemius,
PKCS#12: the guard sees text, not files), and gitleaks' global allowlist (secrets.v2.yaml has its own).
"""

from __future__ import annotations

import re
import sys
import tomllib
import urllib.request
from pathlib import Path

import yaml

COMMIT = "b58d3f102cf3a2c84cb7f923d05c25c9b1aed84b"  # gitleaks master, 2026-07-22
SOURCE = f"https://raw.githubusercontent.com/gitleaks/gitleaks/{COMMIT}/config/gitleaks.toml"
OUT = Path(__file__).with_name("providers.gitleaks.yaml")
SKIP = {"generic-api-key"}
# Most rules end with "followed by a quote, space, `;` or line end", which fits source code. In chat,
# answers and logs a key is often followed by `,` `.` `)` and the like ("your key (pul-…) is valid"),
# so those end a key too.
STRICT_END = r"""(?:[\x60'"\s;]|\\[nr]|$)"""
PROSE_END = r"""(?:[\x60'"\s;,.)\]}>]|\\[nr]|$)"""

LICENSE = f"https://raw.githubusercontent.com/gitleaks/gitleaks/{COMMIT}/LICENSE"


def header(licence: str) -> str:
    """Provenance, then gitleaks' licence verbatim (MIT asks for its notice in copies)."""
    quoted = "\n".join(f"#   {line}".rstrip() for line in licence.strip().splitlines())
    return (
        f"# GENERATED by policies/rules/import_gitleaks.py from gitleaks {COMMIT[:12]}; don't edit by hand.\n"
        f"# Source: {SOURCE}\n"
        "#\n"
        "# Provider credential formats from gitleaks (https://github.com/gitleaks/gitleaks), used under its\n"
        "# licence, reproduced here:\n"
        "#\n"
        f"{quoted}\n"
        "#\n"
        "# Changes on import: the generic catch-all rule, rules scoped to file paths and gitleaks' global\n"
        "# allowlist are left out (secrets.v2.yaml has its own); repeated or alternative capture groups are\n"
        "# resolved as described in import_gitleaks.py; the end-of-key context also accepts , . ) ] } >.\n"
        "# Included by secrets.v2.yaml after its own rules, so a hand-written rule names the placeholder\n"
        "# when both match. Labels are the gitleaks rule id in upper case (`<GITLAB_PAT_1>`).\n"
    )


CAPTURE = re.compile(r"(?<!\\)\((?!\?)")


def first_group_is_repeated(pattern: str) -> bool:
    """Whether the first capturing group is followed by a quantifier (`(...)+`, `(...){2}`)."""
    m = CAPTURE.search(pattern)
    if not m:
        return False
    depth, i = 0, m.start()
    while i < len(pattern):
        c = pattern[i]
        if c == "\\":
            i += 2
            continue
        if c == "[":  # skip a character class, where parentheses are literal
            i += 1
            while i < len(pattern) and pattern[i] != "]":
                i += 2 if pattern[i] == "\\" else 1
        elif c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return pattern[i + 1 : i + 2] in ("+", "*", "{", "?")
        i += 1
    return False


def label_for(rule_id: str) -> str:
    label = re.sub(r"[^A-Z0-9]+", "_", rule_id.upper()).strip("_")
    return label if label[:1].isalpha() else f"KEY_{label}"  # placeholders start with a letter


def convert(rule: dict) -> dict | None:
    if rule["id"] in SKIP or "regex" not in rule or "path" in rule:
        return None
    out: dict = {"id": f"gl_{rule['id'].replace('-', '_')}", "label": label_for(rule["id"])}
    out["pattern"] = rule["regex"].replace(STRICT_END, PROSE_END)
    # Written for Go's RE2: compiled with RE2 (linear time). A backtracking engine took seconds on
    # crafted input for several of these.
    out["engine"] = "re2"
    group = rule.get("secretGroup")
    if group is None and first_group_is_repeated(rule["regex"]):
        group = 0  # e.g. teams: `([a-z0-9]{4}-)+` would report one repetition, not the URL
    elif group is None and CAPTURE.search(rule["regex"]):
        group = "first"  # as gitleaks: the first group that matched (alternatives use different ones)
    if group is not None:
        out["group"] = group
    if "entropy" in rule:
        out["min_entropy"] = float(rule["entropy"])
    if rule.get("keywords"):
        out["keywords"] = sorted({k.lower() for k in rule["keywords"]})
    excludes = [
        pattern
        for allow in rule.get("allowlists", [])
        # Value allowlists only: path conditions don't apply to text, and "match"/"line" targets
        # would need the surrounding text.
        if "paths" not in allow and allow.get("regexTarget", "secret") == "secret"
        for pattern in allow.get("regexes", [])
    ]
    if excludes:
        out["exclude"] = excludes
    return out


def main() -> int:
    with urllib.request.urlopen(SOURCE, timeout=60) as response:
        catalogue = tomllib.loads(response.read().decode())
    with urllib.request.urlopen(LICENSE, timeout=60) as response:
        licence = response.read().decode()
    rules = [r for r in (convert(rule) for rule in catalogue["rules"]) if r is not None]
    body = yaml.safe_dump(
        {"name": "providers_gitleaks", "source": SOURCE, "rules": rules},
        sort_keys=False,
        allow_unicode=True,
        width=10_000,
    )
    OUT.write_text(header(licence) + "\n" + body, encoding="utf-8")
    print(f"wrote {OUT.name}: {len(rules)} rules from {len(catalogue['rules'])} (gitleaks {COMMIT[:12]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
